PYTHONPATH=. python -m lg3.extract_forecasting_data \
  --input_dir "lg3/data/processed" \
  --save_path "lg3/data/forecasting/Tin128_Tout24_Lag3d_7d1_14d1/" \
  --seq_len 288 \
  --pred_len 24 \
  --enc_in -1 \
  --gpu 0 \
  --batch_size 256 \
  --compression_factor 4 \
  --trained_vqvae_model_path "data/TOTEM_data_and_pretrained_tokenizers/generatlist_pretrained_tokenizers/forecasting/CD64_CW256_CF4_BS4096_ITR120000/checkpoints/final_model.pth" \
  --use_lagged \
  --lag_days "0,7,14" \
  --lag_window_days "3,1,1" \
  --steps_per_day 24 \
  --use_sep_token
